# Generated by Django 3.2.16 on 2023-01-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_api", "0002_profilefeeditem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profilefeeditem",
            old_name="create_on",
            new_name="created_on",
        ),
    ]
